In [135]:
import pandas as pd
#from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import mean_squared_error
import numpy as np
import os

from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingRegressor

In [121]:



df_sample = pd.read_csv("data/sample.csv")
#sample = open("data/sample.csv")
#sample = open(os.path.join(os.getcwd(),"data/sample.csv"))

df_train_feats = pd.read_csv("data/train_features.csv")
df_train_labels = pd.read_csv("data/train_labels.csv")
df_test_feats = pd.read_csv("data/test_features.csv")

df_labels_cols = list(df_train_labels)

feats_list2 = [
 'Age',
 'EtCO2',
 'PTT',
 'BUN',
 'Lactate',
 'Temp',
 'Hgb',
 'HCO3',
 'BaseExcess',
 'RRate',
 'Fibrinogen',
 'Phosphate',
 'WBC',
 'Creatinine',
 'PaCO2',
 'AST',
 'FiO2',
 'Platelets',
 'SaO2',
 'Glucose',
 'ABPm',
 'Magnesium',
 'Potassium',
 'ABPd',
 'Calcium',
 'Alkalinephos',
 'SpO2',
 'Bilirubin_direct',
 'Chloride',
 'Hct',
 'Heartrate',
 'Bilirubin_total',
 'TroponinI',
 'ABPs',
 'pH']

subtask1_labels = [
 'LABEL_BaseExcess',
 'LABEL_Fibrinogen',
 'LABEL_AST',
 'LABEL_Alkalinephos',
 'LABEL_Bilirubin_total',
 'LABEL_Lactate',
 'LABEL_TroponinI',
 'LABEL_SaO2',
 'LABEL_Bilirubin_direct',
 'LABEL_EtCO2'
        ]

subtask2_labels = [
 'LABEL_Sepsis'
 ]

subtask3_labels = [
 'LABEL_RRate',
 'LABEL_ABPm',
 'LABEL_SpO2',
 'LABEL_Heartrate'
        ]


def feats_2_X(df_feats,feats_list):
    #Subtask1
    n_derived_feats = 4

    #pids = np.unique(df_train_feats['pid'].values)
    pids = pd.unique(df_feats['pid'])
    n_patients = len(pids)
    #df_train_feats2 = pd.DataFrame(data={'pid':pids})

    print(n_patients)
    print(n_derived_feats*len(feats_list))
    X = np.zeros((n_patients,n_derived_feats*len(feats_list)))

    for i in range(0,n_patients):
        patient_df = df_feats[df_feats['pid']==pids[i]]
        for j in range(0,len(feats_list)):
           patient_feat = patient_df[feats_list[j]].values
           j0 = j*n_derived_feats
           X[i][j0+0] = np.mean(patient_feat)
           X[i][j0+1] = np.std(patient_feat)
           X[i][j0+2] = np.min(patient_feat)
           X[i][j0+3] = np.max(patient_feat)
        #print(patient_df)
        if i%500==0:
            print(i)
    return(X)

In [104]:

X_train = feats_2_X(df_train_feats,feats_list2)

18995
140
0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500
13000
13500
14000
14500
15000
15500
16000
16500
17000
17500
18000
18500

In [105]:
X_test = feats_2_X(df_test_feats,feats_list2)

12664
140
0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500

In [157]:

def impute(X_train,X_test):
    imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp_mean.fit(X_train)
    
    X_train_imp = imp_mean.transform(X_train)
    X_test_imp = imp_mean.transform(X_test)

    #print(X_train_imp)
    return(X_train_imp,X_test_imp)

In [158]:
print(np.shape(X_train))
print(np.shape(X_test))
X_train_imp,X_test_imp = impute(X_train,X_test)

(18995, 140)
(12664, 140)

In [160]:
print(np.shape(X_train_imp))
print(np.shape(X_test_imp))

(18995, 56)
(12664, 56)

In [161]:
count = 0
for i in range(np.shape(X_train)[1]):
    a = np.count_nonzero(~np.isnan(X_train[:,i]))
    print(a)
    if a>0:
        count+=1

18995
18995
18995
18995
49
49
49
49
0
0
0
0
0
0
0
0
0
0
0
0
993
993
993
993
0
0
0
0
0
0
0
0
8
8
8
8
2847
2847
2847
2847
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
8
8
8
0
0
0
0
2
2
2
2
12
12
12
12
2951
2951
2951
2951
0
0
0
0
0
0
0
0
2256
2256
2256
2256
0
0
0
0
0
0
0
0
2868
2868
2868
2868
0
0
0
0
0
0
0
0
0
0
0
0
3197
3197
3197
3197
0
0
0
0
0
0
0
0
2751
2751
2751
2751
10
10
10
10

In [162]:
print(count)

56

In [203]:
def fit_model1(X_train,y_train):
    print(np.shape(y_train))
    print(np.sum(y_train))
    clf = GradientBoostingClassifier(n_estimators=10, learning_rate=1.0, 
                                     max_depth=1, random_state=42).fit(X_train,y_train)
    #clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, 
    #                                 max_depth=5, random_state=42).fit(X_train_imp,y_train)

    return(clf)


def fit_model3(X_train,y_train):
    #print(np.shape(y_train))
    #print(np.sum(y_train))
    reg = GradientBoostingRegressor(random_state=42).fit(X_train,y_train)

    return(reg)

In [204]:


#print(np.shape(y_train))

test_pids = pd.unique(df_test_feats['pid'])
#y_test = np.zeros((len(test_pids),1+len(subtask1_labels)))
#y_test[:,0] = test_pids

df_test_labels = pd.DataFrame(columns=df_labels_cols)
df_test_labels['pid'] = test_pids

In [205]:
for i in range(0,len(subtask1_labels)):
#for i in range(0,1):
    y_train=df_train_labels[subtask1_labels[i]].values
    clf = fit_model1(X_train_imp,y_train)
    
    score = clf.score(X_train_imp,y_train)
    print(score)
    p_train=clf.predict_proba(X_train_imp)
    #print(p)
    print(np.sum(p_train[:,0]))
    print(np.sum(p_train[:,1]))
    
    p_test=clf.predict_proba(X_test_imp)
    print(np.sum(p_test[:,0]))
    print(np.sum(p_test[:,1]))
    
    #y_test[:,1+i] = p_test[:,1]
    
    df_test_labels[subtask1_labels[i]] = p_test[:,1]

(18995,)
5096.0
0.7606212161095025
13899.331863949825
5095.668136050174
9259.216689887766
3404.7833101122333
(18995,)
1400.0
0.9265596209528824
17585.999999960655
1409.000000039346
11722.926081774796
941.0739182252044
(18995,)
4554.0
0.7605685706764939
14440.99942997177
4554.0005700282345
9643.77869887021
3020.221301129791
(18995,)
4487.0
0.7639905238220585
14504.668398997306
4490.331601002694
9682.027011702794
2981.9729882972065
(18995,)
4570.0
0.7596209528823374
14425.00011150954
4569.999888490461
9624.314952272676
3039.6850477273247
(18995,)
3803.0
0.8005790997630956
15188.584726636213
3806.415273363784
10124.166960847031
2539.833039152968
(18995,)
1895.0
0.9002369044485391
17098.1374007531
1896.8625992469015
11395.391889840152
1268.6081101598502
(18995,)
4439.0
0.7883127138720716
14551.338167243259
4443.661832756741
9688.173074460548
2975.8269255394516
(18995,)
644.0
0.9663069228744406
18349.312961809494
645.6870381905089
12233.642414278955
430.35758572104817
(18995,)
1254.0
0.936509607791524
17741.999999999232
1253.0000000007653
11831.442567073202
832.5574329267962

In [206]:
for i in range(0,len(subtask2_labels)):
#for i in range(0,1):
    y_train=df_train_labels[subtask2_labels[i]].values
    clf = fit_model1(X_train_imp,y_train)
    
    score = clf.score(X_train_imp,y_train)
    print(score)
    p_train=clf.predict_proba(X_train_imp)
    #print(p)
    print(np.sum(p_train[:,0]))
    print(np.sum(p_train[:,1]))
    
    p_test=clf.predict_proba(X_test_imp)
    print(np.sum(p_test[:,0]))
    print(np.sum(p_test[:,1]))
    
    #y_test[:,1+i] = p_test[:,1]
    
    df_test_labels[subtask2_labels[i]] = p_test[:,1]

(18995,)
1088.0
0.9425638325875231
17894.000000000004
1101.0
11931.20974654218
732.7902534578233

In [207]:
for i in range(0,len(subtask3_labels)):
#for i in range(0,1):
    print("i=%d"%i)
    y_train=df_train_labels[subtask3_labels[i]].values
    reg = fit_model3(X_train_imp,y_train)
    
    score = reg.score(X_train_imp,y_train)
    print("score: %f"%score)
    
    y_train_pred=reg.predict(X_train_imp)
    print(np.mean(y_train_pred))
    print(np.std(y_train_pred))
    
    y_test=reg.predict(X_test_imp)
    print(np.mean(y_test))
    print(np.std(y_test))
    
    df_test_labels[subtask3_labels[i]] = y_test

i=0
score: 0.091077
18.795959655719557
0.88814771355344
18.804193883775543
0.9076460802737815
i=1
score: 0.142086
82.5111709400038
4.555625427192507
82.47866065382539
4.521377389757354
i=2
score: 0.106776
96.9473109628804
0.5810127115103902
96.93899835483622
0.5921513441322713
i=3
score: 0.116325
84.11971626206534
4.680485981246938
84.04651426475735
4.657149009496807

In [208]:
print(test_pids)
print(y_test)
print(df_test_labels)
print(np.sum(df_test_labels['LABEL_BaseExcess']))

[    0 10001 10003 ...  9992  9994  9997]
[87.83661849 83.23183239 82.20873867 ... 83.68157256 98.74895279
 83.46437515]
         pid  LABEL_BaseExcess  LABEL_Fibrinogen  LABEL_AST  \
0          0          0.196105          0.077269   0.290994
1      10001          0.196105          0.077269   0.230604
2      10003          0.238238          0.077269   0.230604
3      10004          0.196105          0.077269   0.290994
4      10005          0.238238          0.056648   0.230604
...      ...               ...               ...        ...
12659   9989          0.267994          0.077269   0.336728
12660   9991          0.196105          0.077269   0.230604
12661   9992          0.800789          0.077269   0.125061
12662   9994          0.754330          0.077269   0.187189
12663   9997          0.196105          0.077269   0.230604

       LABEL_Alkalinephos  LABEL_Bilirubin_total  LABEL_Lactate  \
0                0.275390               0.276892       0.162641
1                0.275390               0.276892       0.190788
2                0.217618               0.226329       0.190788
3                0.275390               0.276892       0.162641
4                0.217618               0.226329       0.190788
...                   ...                    ...            ...
12659            0.430109               0.402435       0.162641
12660            0.275390               0.276892       0.190788
12661            0.116501               0.113563       0.391027
12662            0.235862               0.132580       0.327054
12663            0.275390               0.276892       0.190788

       LABEL_TroponinI  LABEL_SaO2  LABEL_Bilirubin_direct  LABEL_EtCO2  \
0             0.070747    0.127920                0.039801     0.079267
1             0.117182    0.192589                0.039801     0.079267
2             0.117182    0.218310                0.039801     0.079267
3             0.117182    0.127920                0.039801     0.079267
4             0.117182    0.218310                0.022397     0.052991
...                ...         ...                     ...          ...
12659         0.062108    0.127920                0.039801     0.031997
12660         0.117182    0.192589                0.039801     0.079267
12661         0.019596    0.629303                0.019245     0.014891
12662         0.060319    0.800102                0.020303     0.014891
12663         0.117182    0.192589                0.039801     0.079267

       LABEL_Sepsis  LABEL_RRate  LABEL_ABPm  LABEL_SpO2  LABEL_Heartrate
0          0.056821    18.531917   87.282365   97.207446        87.836618
1          0.056821    18.618516   83.590995   96.871141        83.231832
2          0.056821    18.940035   81.548564   96.847595        82.208739
3          0.056821    18.531917   87.282365   97.124869        86.058002
4          0.056821    19.197299   80.086279   96.847595        80.881657
...             ...          ...         ...         ...              ...
12659      0.056821    19.448651   87.563327   95.699257       101.425165
12660      0.056821    18.618516   83.590995   96.871141        83.231832
12661      0.056821    18.776315   66.446131   96.970097        83.681573
12662      0.056821    17.326805   85.223497   98.771030        98.748953
12663      0.056821    18.531917   84.776946   96.871141        83.464375

[12664 rows x 16 columns]
3404.7833101122333

In [196]:
df_test_labels = df_test_labels.set_index('pid')

In [197]:
list(df_test_labels)

['LABEL_BaseExcess',
 'LABEL_Fibrinogen',
 'LABEL_AST',
 'LABEL_Alkalinephos',
 'LABEL_Bilirubin_total',
 'LABEL_Lactate',
 'LABEL_TroponinI',
 'LABEL_SaO2',
 'LABEL_Bilirubin_direct',
 'LABEL_EtCO2',
 'LABEL_Sepsis',
 'LABEL_RRate',
 'LABEL_ABPm',
 'LABEL_SpO2',
 'LABEL_Heartrate']

In [209]:
df_train_labels

,pid,LABEL_BaseExcess,LABEL_Fibrinogen,LABEL_AST,LABEL_Alkalinephos,LABEL_Bilirubin_total,LABEL_Lactate,LABEL_TroponinI,LABEL_SaO2,LABEL_Bilirubin_direct,LABEL_EtCO2,LABEL_Sepsis,LABEL_RRate,LABEL_ABPm,LABEL_SpO2,LABEL_Heartrate
0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,12.1,85.4,100.0,59.9
1,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.8,100.6,95.5,85.5
2,100,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,16.5,88.3,96.5,108.1
3,1000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,19.4,77.2,98.3,80.9
4,10000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.6,76.8,97.7,95.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18990,9993,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,17.1,69.8,100.0,110.7
18991,9995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.6,97.3,97.8,59.2
18992,9996,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,17.3,66.3,96.9,100.3
18993,9998,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,18.8,81.5,96.9,99.4
18994,9999,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,18.0,95.5,97.0,81.9

In [173]:
df_test_labels['LABEL_BaseExcess']

pid
0        0.196105
10001    0.196105
10003    0.238238
10004    0.196105
10005    0.238238
           ...
9989     0.267994
9991     0.196105
9992     0.800789
9994     0.754330
9997     0.196105
Name: LABEL_BaseExcess, Length: 12664, dtype: float64

['pid',
 'LABEL_BaseExcess',
 'LABEL_Fibrinogen',
 'LABEL_AST',
 'LABEL_Alkalinephos',
 'LABEL_Bilirubin_total',
 'LABEL_Lactate',
 'LABEL_TroponinI',
 'LABEL_SaO2',
 'LABEL_Bilirubin_direct',
 'LABEL_EtCO2',
 'LABEL_Sepsis',
 'LABEL_RRate',
 'LABEL_ABPm',
 'LABEL_SpO2',
 'LABEL_Heartrate']

In [183]:
#for col in list(df_test_labels):
#    df_test_labels[col] = df_test_labels[col].astype('float16')

In [188]:
df_test_labels.round(decimals=2)

,LABEL_BaseExcess,LABEL_Fibrinogen,LABEL_AST,LABEL_Alkalinephos,LABEL_Bilirubin_total,LABEL_Lactate,LABEL_TroponinI,LABEL_SaO2,LABEL_Bilirubin_direct,LABEL_EtCO2,LABEL_Sepsis,LABEL_RRate,LABEL_ABPm,LABEL_SpO2,LABEL_Heartrate
pid,,,,,,,,,,,,,,,
0,0.199951,0.080017,0.290039,0.280029,0.280029,0.160034,0.070007,0.130005,0.040009,0.080017,0.059998,18.531250,87.2500,97.1875,87.8125
10001,0.199951,0.080017,0.229980,0.280029,0.280029,0.189941,0.119995,0.189941,0.040009,0.080017,0.059998,18.625000,83.6250,96.8750,83.2500
10003,0.239990,0.080017,0.229980,0.219971,0.229980,0.189941,0.119995,0.219971,0.040009,0.080017,0.059998,18.937500,81.5625,96.8750,82.1875
10004,0.199951,0.080017,0.290039,0.280029,0.280029,0.160034,0.119995,0.130005,0.040009,0.080017,0.059998,18.531250,87.2500,97.1250,86.0625
10005,0.239990,0.059998,0.229980,0.219971,0.229980,0.189941,0.119995,0.219971,0.020004,0.049988,0.059998,19.203125,80.0625,96.8750,80.8750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,0.270020,0.080017,0.340088,0.429932,0.399902,0.160034,0.059998,0.130005,0.040009,0.029999,0.059998,19.453125,87.6250,95.6875,101.4375
9991,0.199951,0.080017,0.229980,0.280029,0.280029,0.189941,0.119995,0.189941,0.040009,0.080017,0.059998,18.625000,83.6250,96.8750,83.2500
9992,0.799805,0.080017,0.119995,0.119995,0.109985,0.389893,0.020004,0.629883,0.020004,0.010002,0.059998,18.781250,66.4375,96.9375,83.6875
9994,0.750000,0.080017,0.189941,0.239990,0.130005,0.330078,0.059998,0.799805,0.020004,0.010002,0.059998,17.328125,85.2500,98.7500,98.7500
9997,0.199951,0.080017,0.229980,0.280029,0.280029,0.189941,0.119995,0.189941,0.040009,0.080017,0.059998,18.531250,84.7500,96.8750,83.4375

In [189]:

df_test_labels['LABEL_BaseExcess'].round(2)

pid
0        0.199951
10001    0.199951
10003    0.239990
10004    0.199951
10005    0.239990
           ...
9989     0.270020
9991     0.199951
9992     0.799805
9994     0.750000
9997     0.199951
Name: LABEL_BaseExcess, Length: 12664, dtype: float16

In [201]:
df_test_labels = df_test_labels.round(3)

In [210]:
df_test_labels

,pid,LABEL_BaseExcess,LABEL_Fibrinogen,LABEL_AST,LABEL_Alkalinephos,LABEL_Bilirubin_total,LABEL_Lactate,LABEL_TroponinI,LABEL_SaO2,LABEL_Bilirubin_direct,LABEL_EtCO2,LABEL_Sepsis,LABEL_RRate,LABEL_ABPm,LABEL_SpO2,LABEL_Heartrate
0,0,0.196105,0.077269,0.290994,0.275390,0.276892,0.162641,0.070747,0.127920,0.039801,0.079267,0.056821,18.531917,87.282365,97.207446,87.836618
1,10001,0.196105,0.077269,0.230604,0.275390,0.276892,0.190788,0.117182,0.192589,0.039801,0.079267,0.056821,18.618516,83.590995,96.871141,83.231832
2,10003,0.238238,0.077269,0.230604,0.217618,0.226329,0.190788,0.117182,0.218310,0.039801,0.079267,0.056821,18.940035,81.548564,96.847595,82.208739
3,10004,0.196105,0.077269,0.290994,0.275390,0.276892,0.162641,0.117182,0.127920,0.039801,0.079267,0.056821,18.531917,87.282365,97.124869,86.058002
4,10005,0.238238,0.056648,0.230604,0.217618,0.226329,0.190788,0.117182,0.218310,0.022397,0.052991,0.056821,19.197299,80.086279,96.847595,80.881657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12659,9989,0.267994,0.077269,0.336728,0.430109,0.402435,0.162641,0.062108,0.127920,0.039801,0.031997,0.056821,19.448651,87.563327,95.699257,101.425165
12660,9991,0.196105,0.077269,0.230604,0.275390,0.276892,0.190788,0.117182,0.192589,0.039801,0.079267,0.056821,18.618516,83.590995,96.871141,83.231832
12661,9992,0.800789,0.077269,0.125061,0.116501,0.113563,0.391027,0.019596,0.629303,0.019245,0.014891,0.056821,18.776315,66.446131,96.970097,83.681573
12662,9994,0.754330,0.077269,0.187189,0.235862,0.132580,0.327054,0.060319,0.800102,0.020303,0.014891,0.056821,17.326805,85.223497,98.771030,98.748953
12663,9997,0.196105,0.077269,0.230604,0.275390,0.276892,0.190788,0.117182,0.192589,0.039801,0.079267,0.056821,18.531917,84.776946,96.871141,83.464375

In [212]:
df_test_labels.to_csv('prediction.zip', index=False, float_format='%.3f', compression='zip')

In [202]:
df_test_labels.to_csv("submission4.csv")